api_platform:
    title: OTP
    version: 1.0.0
    formats:
        json: [ "application/json" ]
        jsonld: [ 'application/ld+json' ]
        html: [ "text/html" ]
        multipart: [ "multipart/form-data" ]
    docs_formats:
        jsonld: [ 'application/ld+json' ]
        jsonopenapi: [ 'application/vnd.openapi+json' ]
        html: [ 'text/html' ]
    swagger:
        versions: [ 3 ]
        api_keys:
            apiKey:
                name: Authorization
                type: header
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    use_symfony_listeners: true
